source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

project 'demo/demo.project'

target :demo do

pod 'Masonry'

end

target :demo1 do
    
    pod 'Masonry'
    
end

target :demo2 do
    
    pod 'Masonry'
    
end

target :demo3 do
    
    pod 'Masonry'
    
end
